config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}, :controllers => { registrations: 'registrations' }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders
  resources :payments
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    delete 'remove/:product_id', to: 'carts#remove', as: :remove_from
    post 'save', to: 'carts#save', as: :save
    get 'count', to: 'carts#count', as: :count
    get 'total', to: 'carts#total'
    delete 'empty', to: 'carts#empty'
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

    root 'static_pages#index'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  EXPIRATION_TIME = 48.hours
  def show
    @items = $redis.hgetall(cart_name)
    @products = Product.find(@items.keys)
    @total = $redis.get("total_#{cart_name}")
  end

  def add

    $redis.hincrby(cart_name,params[:product_id],1)
    $redis.expire(cart_name,EXPIRATION_TIME)
    increase_count(1)
    increase_total(params[:product_price])
    respond_to do |format|
      format.js
    end
  end
  def empty
    empty_cart
    redirect_to :back
  end

  def remove
    quantity = $redis.hget(cart_name,params[:product_id])
    price = Product.find(params[:product_id]).price
    $redis.hdel(cart_name,params[:product_id])
    increase_total(-(price.to_f * quantity.to_f))
    increase_count(- quantity.to_i)
    respond_to do|format|
      format.json { render json: {status: "ok", message: "Success!", id: params[:product_id] }}
    end
  end
  def save
    @order = Order.new(user_id: current_user.id, total: $redis.get("total_#{cart_name}") )
    $redis.hgetall(cart_name).each do |key,value|
      @product = Product.find(key)
      value.to_i.times {@order.products << @product}
    end
    empty_cart
    @order.save
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Order was successfully created.' }
    end
  end
  def count
    count = $redis.get("count_#{cart_name}") || 0
    respond_to do |format|
      format.json { render json: count }
    end
  end
  def total
    total = $redis.get("total_#{cart_name}")
    respond_to do |format|
      format.json { render json: total }
    end
  end
  private

  def empty_cart
    $redis.del(cart_name)
    $redis.del("total_#{cart_name}")
    $redis.del("count_#{cart_name}")
  end
  def cart_name
    "cart_#{current_user.id}"
  end
  def increase_total(amount)
    $redis.incrbyfloat("total_#{cart_name}", amount.to_f)
    $redis.expire("total_#{cart_name}",EXPIRATION_TIME)
  end
  def increase_count(quantity)
    $redis.incrby("count_#{cart_name}", quantity)
    $redis.expire("count_#{cart_name}",EXPIRATION_TIME)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/add.js.erb
$("#addToCart").on("ajax:success", function(e, data, status, xhr){
  $("#ajax-response").removeClass("alert alert-danger")
  $("#ajax-response").addClass("alert alert-success").text("Item added to the cart");
  cartCount();
}
).on("ajax:error", function(e, xhr, status, error){
  $("#ajax-response").removeClass("alert alert-success")
  $("#ajax-response").addClass("alert alert-danger").text("There was an error with your purchase");
});

app/views/carts/remove.js.erb
$("#removeFromCart").on("ajax:success", function(e, data, status, xhr){
  $(this).closest("tr").remove();
  cartCount();
}
).on("ajax:error", function(e, xhr, status, error){
 
});

app/views/carts/show.html.erb
<div class="container">
<h1 class="fancy">Cart</h1>
<table class="table table-striped">
<tr>
  <th>
    Product
  </th>
  <th>
    Price
  </th>
  <th>
    Quantity
  </th>
  <th>
    Action
  </th>
</tr>
<% @products.each do |product| %>
<tr id="removeFromCart_<%= product.id %>">
  <td>
    <%= product.name %>
  </td>
  <td>
    <%= number_to_currency(product.price, precision: 2, locale: :de) %>
  </td>
  <td>
    <%= @items[product.id.to_s] %> 
  </td>
  <td>
    <button  class="btn btn-default removeFromCart" data-product="<%= product.id %>">Remove</button>

  </td>
</tr>
<% end %>
<tr>
  <td colspan="3">
    Total: <span id="cartTotal"><%= number_to_currency($redis.get("total_cart_#{current_user.id}"), precision: 2, locale: :de) %></span>
  </td>
  <td>
    <%= link_to 'Place Order' ,  save_cart_path, method: :post, class: "btn btn-default" %>
  </td>

</tr>
</table>
<%= link_to 'Empty Cart' ,  empty_cart_path, method: :delete, class: "btn btn-danger" %>
</div>