config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}, :controllers => { registrations: 'registrations' }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders
  resources :payments
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    delete 'remove/:product_id', to: 'carts#remove', as: :remove_from
    post 'save', to: 'carts#save', as: :save
    get 'count', to: 'carts#count', as: :count
    get 'total', to: 'carts#total'
    delete 'empty', to: 'carts#empty'
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

    root 'static_pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :orders
  has_many :comments
  scope :search, -> (search_term){ where("lower(name) LIKE ? OR lower(description) LIKE ?", "%#{search_term.downcase}%", "%#{search_term.downcase}%") }

  validates :name, presence: true
  
  def average_rating
    comments.average(:rating).to_f
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q] 
      @products = Product.search(search_term)
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "control-label" %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :colour %><br>
    <%= f.select(
      :colour,
      [['White', 'white'], ['Red', 'red'], ['Black','black'],['Yellow','yellow'],['Orange','orange'],['Pink','pink']],
      {},
      class: 'chosen-select'
    ) %>

  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="form-group">
    <%= f.label :image_url,class: "control-label"  %><br>
    <%= f.text_field :image_url,class: "form-control", id: "image_url" %>
  </div>
  <div class="image">

  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
    <h4>Add a review:</h4>
    <%= form_for([@product, @product.comments.build]) do |f| %>

      <div class="form-group">
        <%= f.label :body, "Comments" %><br>
        <%= f.text_area :body, class: "form-control"%>
      </div>
      <div class="form-group">
        <div class="rating"></div>
      </div> 
      <%= f.submit  "Submit",class: "btn btn-default" %>

    <% end %>
<% end %>  

app/views/products/_product.html.erb
 <% cache(product) do %>
  <section class="product">
    <div class="row">
      <div class="col-xs-12 col-md-5 col-md-offset-1">
        <h2><%= product.name %></h2>

        <p>Average Rating: <span class="rated" data-score="<%= product.average_rating %>"></span> </p>

        <p>Color: <%= product.colour %></p>
        <p> Price: <%= number_to_currency(product.price, precision: 2, locale: :de) %></p>
        <p>
          <%=h truncate(product.description, length: 200, omission: " ", separator: " ") { link_to "more...", product } %>
        </p>
        <div class="btn-group btn-group-xs" role="group" aria-label="...">
          <%= link_to 'Show', product, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_product_path(product),class: "btn btn-default" %>
          <!-- <a href="#" id="description" class="btn btn-default toggleDesc">Description</a> -->
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
        </div>
      </div>
      <div class="col-xs-12 col-md-5">
        <%= image_tag(product.image_url, class:"img-responsive img-product", alt: "image not found" ) %>
      </div>
    </div>
  </section>
<% end %>

app/views/products/_product_reviews.html.erb
<div class="product-reviews">
    <%= will_paginate @comments %>
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
            <% if signed_in? && current_user.admin? %>
                <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
  <h1>Editing Product</h1>
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <%= render 'form' %>
    </div>
  </div>
  <ul class="nav nav-pills">
    <li role="presentation"><%= link_to 'Show', @product %></li>
    <li role="presentation"><%= link_to 'Back', products_path %></li>
  </ul>

</div>

app/views/products/index.html.erb
<div class="container">
  <div id="row">
    <% if alert %> 
    <p id="alert" class="alert alert-danger" role="alert"><%= alert %></p>
    <% elsif notice %>
    <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
    <% end %>
  </div>
  <div class="row">
    <h1 class="fancy">Products</h1>
    <% cache_unless(params[:q],cache_key_for_products) do %>
      <%= render partial: "product", collection: @products %>
    <% end %>
  </div>
  <%= link_to 'New Product', new_product_path, class: "btn btn-default new-product" %>

</div>

app/views/products/new.html.erb
<div class="container">
  <h1>New Product</h1>
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <%= render 'form' %>
    </div>
  </div>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
  <% elsif alert %>
    <div class="alert alert-danger" role="alert"><%= alert %></div>
  <% end %>
  <div id="ajax-response"></div>
  <h1>
    <%= @product.name %>
  </h1>

  <div class="row">
    <div class="col-xs-12 col-md-6">
      <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>
      <p>Color: <%= @product.colour %></p>
      <p> 
        Price: <%= number_to_currency(@product.price, precision: 2, locale: :de) %>
        <%= form_tag("/cart/add/#{@product.id}", {remote: true , method: :put, id: "addToCart"} ) do %>
          <%= hidden_field_tag(:product_price, @product.price) %>
          <%= hidden_field_tag(:authenticity_token, form_authenticity_token) %>
          <%= button_tag(type: "submit", class: "btn btn-default") do %>
            Add to cart <i class="fa fa-shopping-cart"></i>
          <% end %>
        <% end %>  
      </p>
      <strong>Description:</strong>
      <%= @product.description %>

    </div>
    <div class="col-xs12 col-md-6">
      <%= image_tag(@product.image_url, alt: "Image not found" ) %>
    </div>

  </div>
  <div class="row">
    <ul class="nav nav-pills">
      <li role="presentation"><%= link_to 'Edit', edit_product_path(@product) %></li>
      <li role="presentation"><%= link_to 'Back', products_path %></li>
    </ul>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= render "new_comment" %> 
      <%= render "product_reviews" %>
    </div>
  </div>

</div>