config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'}, :controllers => { registrations: 'registrations' }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders
  resources :payments
  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    delete 'remove/:product_id', to: 'carts#remove', as: :remove_from
    post 'save', to: 'carts#save', as: :save
    get 'count', to: 'carts#count', as: :count
    get 'total', to: 'carts#total'
    delete 'empty', to: 'carts#empty'
  end

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

    root 'static_pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="bikeblnApp">
<head>
  <title>Bike Berlin</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Sigmar+One' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>


</head>
<body>
<nav class="navbar  navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button id="toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <a class="navbar-brand" href="/">Bike <span class="fa fa-bicycle"></span>  Berlin</a>
      <%= form_tag("/products", method: "get",class: "navbar-form navbar-right") do %>
        <div class="form-group">
          <%= label_tag(:q, "Search for:",class: "control-label") %>
          <%= text_field_tag(:q,nil, class: "form-control") %>
        </div>
        <%= submit_tag("Search",class: "btn btn-default btn-xs") %>
      <% end %>
      <ul class="nav navbar-nav">
        <li><a href="#about">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "New", new_product_path %></li>
            <li><%= link_to "List", products_path %></li>
          </ul>
        </li>

        <li><a href="/static_pages/contact">Contact</a></li>
        <% if user_signed_in? %>
        <li><%= link_to "Orders", orders_path %></li>
        <li>
          <%= link_to cart_path do%>
            <span id="cart-count"></span>
            <i class="fa fa-shopping-cart"></i>
          <% end %>
        </li>
        <li>
          <%= link_to("Profile",current_user) %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
        <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>
<%= yield %>
<footer>
  <p>Welcome! The date and time is <%= Time.zone.now %></p>
</footer>
</body>
</html>